### ISSUE TITLE
Spline100-Spline256 are not the actual Spline100-256 kernels

### ISSUE THREAD

**Issue by wiwaz** [Irrational-Encoding-Wizardry/vs-kernels#12]
Fmtconv's `spline` works differently from the Spline100, Spline144, etc resizers found in other applications, they do not produce the same results. These kernels can be seen as entirely different and as such they should be made to match the original Spline kernels or just removed entirely.

**Comment by Setsugennoao** [comment]
how do i make them match the original spline?
