### ISSUE TITLE
placebo.Resample support

### ISSUE THREAD

**Issue by NSQY** [Irrational-Encoding-Wizardry/vs-kernels#3]
The main benefit here would be elliptical (EWA) kernel support, such as ewa_lanczos or ewa_robidoux*. From memory Robidoux kernels were intended to be EWA, there are posts on the imagemagick forum about this but I cannot find them at the moment.

With the placebo.Resample filter parameter, make sure not to accidentally use the 'bicubic' filter; it's actually some kind of 'fast' bicubic kernel which is extremely blurry and not configurable.

**Comment by Setsugennoao** [comment]
Thanks for opening the issue!
Implemented the new kernels in [#c303880](https://github.com/Irrational-Encoding-Wizardry/vs-kernels/commit/c30388004df8d237e5b48d785e998f5b3a9c51ca)
