### ISSUE TITLE
requirements, vstools>=2.0.5 but https://github.com/Irrational-Encoding-Wizardry/vs-tools only has 1.3.0

### ISSUE THREAD

**Issue by hydra3333** [Irrational-Encoding-Wizardry/vs-kernels#5]
Hello. Nice job.

Of interest, requirements.txt mentions  vstools>=2.0.5 
however over at https://github.com/Irrational-Encoding-Wizardry/vs-tools the latest release is only 1.3.0.

Am I looking at the right place and at the right vstools ?

Thanks.

**Comment by Setsugennoao** [comment]
Hi, github releases are manual so I just never bothered keeping up with them.
You can look at tags and pypi releases.
