### ISSUE TITLE
Placebo kernels limitations

### ISSUE THREAD

**Issue by wiwaz** [Irrational-Encoding-Wizardry/vs-kernels#6]
Radius, param1, param2, and wparam are not configurable.

Scalings that are possible using the plugin directly are not possible within vskernels
For example:
`clip = vskernels.EwaRobidoux(b=50, c=50).scale(clip, 960, 540)` will error with `TypeError: Placebo.__init__() got multiple values for argument 'b'`
but
`clip = core.placebo.Resample(clip, 960, 540, filter="ewa_robidoux", param1=50, param2=50)` works just fine.

**Comment by Setsugennoao** [comment]
Last i checked, the parameters don't change anything, thay's why it doesn't allow you to change them via kwargs

**Comment by wiwaz** [comment]
Incorrect, the parameters function as they should.

**Comment by Setsugennoao** [comment]
why is bicubic named robidoux

**Comment by NSQY** [comment]
Because ``bicubic`` in libplacebo is a non-configurable frankensteinian kernel. We must also pay our respects to sir Nicolas Robidoux.

**Comment by Setsugennoao** [comment]
The radius is just `taps` 👍🏻
