### ISSUE TITLE
Add sigmoidize and linearize options to all scalers

### ISSUE THREAD

**Issue by wiwaz** [Irrational-Encoding-Wizardry/vs-kernels#7]

**Comment by Setsugennoao** [comment]
Elaborate

**Comment by NSQY** [comment]
He wants this for all kernels so you don't need to manually wrap the kernel within a inverse/direct transfer.

https://github.com/Irrational-Encoding-Wizardry/vs-kernels/blob/531de9b9bf58d66727a332c8a960f2bddf1d0fe8/vskernels/kernels/placebo.py#L36-L40

`vskernels.Hermite.scale(clip, linearize=True, curve=Transfer.BT709, sigmoid=(0.75, 6.5))`

**Comment by Setsugennoao** [comment]
This seems out of scope for the base Scaler class.
What seems more appropriate is a class that inherits from a scaler and uses thst or just takes the one you want to use as parameter

Like LinearScale(Hermite).scale(...)

**Comment by Vodes** [comment]
[german engineering common w](https://github.com/Vodes/vodesfunc/blob/master/vodesfunc/scale.py#L20-L90)

**Comment by Setsugennoao** [comment]
rapeware

**Comment by Setsugennoao** [comment]
Added https://github.com/Irrational-Encoding-Wizardry/vs-kernels/compare/59aa4e0bb436c195e8dc11c2697f295bcf1337ff...e89f29fcbaa7c7e31229dd2f45fcce234a38cc59
